// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDCnsqGcvF7J5KGyjJgIjer7TSmCJPJyI',
    appId: '1:618402510524:web:bdc135e353d40e580782b9',
    messagingSenderId: '618402510524',
    projectId: 'hakbay-4c151',
    authDomain: 'hakbay-4c151.firebaseapp.com',
    storageBucket: 'hakbay-4c151.firebasestorage.app',
    measurementId: 'G-X5MDZGRC1L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7y-V4bVz_zETZG4lGnvRtWm8WDKy7ZiY',
    appId: '1:618402510524:android:435bbd0ffce32f1c0782b9',
    messagingSenderId: '618402510524',
    projectId: 'hakbay-4c151',
    storageBucket: 'hakbay-4c151.firebasestorage.app',
  );
}
